// components/general/navbar.vue
<template>
    <header class="flex justify-between items-center m-4 mb-8 z-10">
        <!-- Menu mobile (Dropdown) -->
        <DropdownMenu v-model:open="open">
            <DropdownMenuTrigger as-child>
                <Button class="sm:hidden" @click="open = !open">Menu</Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent>
                <DropdownMenuItem v-for="route in routes" :key="route.name">
                    <NuxtLink :to="route.href" class="text-sm font-medium transition-colors hover:text-primary"
                        :class="{ 'text-primary': route.href === currentPath, 'text-muted-foreground': route.href !== currentPath }"
                        @click="open = false">
                        {{ route.name }}
                    </NuxtLink>
                </DropdownMenuItem>
            </DropdownMenuContent>
        </DropdownMenu>

        <!-- Menu desktop -->
        <NavigationMenu class="hidden sm:block">
            <NavigationMenuList class="flex gap-4">
                <NavigationMenuItem v-for="route in routes" :key="route.name">
                    <NavigationMenuLink as-child>
                        <NuxtLink :to="route.href" class="text-sm font-medium transition-colors hover:text-primary"
                            :class="{ 'text-primary': route.href === currentPath, 'text-muted-foreground': route.href !== currentPath }">
                            {{ route.name }}
                        </NuxtLink>
                    </NavigationMenuLink>
                </NavigationMenuItem>
            </NavigationMenuList>
        </NavigationMenu>

        <!-- Theme Toggle -->
        <ThemeToggle />
    </header>
</template>

<script setup lang="ts">
import { ref, computed } from "vue";
import { useRoute } from "vue-router";
import {
    NavigationMenu,
    NavigationMenuList,
    NavigationMenuItem,
    NavigationMenuLink,
} from "@/components/ui/navigation-menu";
import {
    DropdownMenu,
    DropdownMenuTrigger,
    DropdownMenuContent,
    DropdownMenuItem,
} from "@/components/ui/dropdown-menu";
import { Button } from "@/components/ui/button";
import ThemeToggle from "./theme-toggle.vue";

// État du menu mobile
const open = ref(false);

// Détection du chemin actuel
const route = useRoute();
const currentPath = computed(() => route.path);

// Liste des routes
const routes = [
    { name: "Accueil", href: "/" },
    { name: "Projets", href: "/projets" },
    { name: "Expériences", href: "/experiences" },
    { name: "Formations", href: "/formations" },
    { name: "Blog", href: "/blog" },
    { name: "Contact", href: "/contact" },
];
</script>

// src/components/general/navbar.tsx
"use client"

import { usePathname } from "next/navigation";
import { ModeToggle } from "./mode-toggle";
import Link from "next/link";
import { NavigationMenu, NavigationMenuList, NavigationMenuItem, NavigationMenuLink } from "@/components/ui/navigation-menu";
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem } from "@/components/ui/dropdown-menu";
import { Button } from "@/components/ui/button";
import { useState } from "react";
export function Navbar() {
    const pathname = usePathname();

    const [open, setOpen] = useState(false);

    const routes = [
        {
            name: "Accueil",
            href: "/",
        },
        {
            name: "Projets",
            href: "/projets",
        },
        {
            name: "Expériences",
            href: "/experiences",
        },
        {
            name: "Formations",
            href: "/formations",
        },
        {
            name: "Contact",
            href: "/contact",
        },
        {
            name: "Blog",
            href: "/blog",
        }
    ];

    return (
        <header className="flex justify-between items-center m-4 mb-8">
            <DropdownMenu open={open} onOpenChange={setOpen}>
                <DropdownMenuTrigger className="sm:hidden" asChild>
                    <Button>Menu</Button>
                </DropdownMenuTrigger>
                <DropdownMenuContent>
                    {routes.map((route: { name: string; href: string }) => (
                        <DropdownMenuItem key={route.name}>
                            <Link onClick={() => setOpen(false)} href={route.href} className={`text-sm font-medium transition-colors hover:text-primary ${pathname === route.href ? 'text-primary' : 'text-muted-foreground'}`}>
                                {route.name}
                            </Link>
                        </DropdownMenuItem>
                    ))}
                </DropdownMenuContent>
            </DropdownMenu>
            <NavigationMenu className="hidden sm:block">
                <NavigationMenuList className="flex flex-col sm:flex-row gap-4">
                    {routes.map((route) => (
                        <NavigationMenuItem key={route.name}>
                            <NavigationMenuLink asChild>
                                <Link href={route.href} className={`text-sm font-medium transition-colors hover:text-primary ${pathname === route.href ? 'text-primary' : 'text-muted-foreground'}`}>
                                    {route.name}
                                </Link>
                            </NavigationMenuLink>
                        </NavigationMenuItem>
                    ))}
                </NavigationMenuList>
            </NavigationMenu>
            <ModeToggle />
        </header>
    )
};
