// pages/blog/index.vue
<template>
    <div class="container mx-auto p-4">
        <h1 class="text-4xl font-bold mb-4">
            Blog
        </h1>
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            <Card v-for="post in posts"
                class="p-4 rounded-lg shadow border-2 border-dark dark:border-white bg-transparent hover:scale-[1.05] cursor-pointer duration-500">
                <NuxtLink :href="`/blog/${post.slug}`" external>
                    <CardHeader>
                        <CardTitle class="text-4xl font-bold mb-4 text-dark dark:text-white">{{ post.title }}</CardTitle>
                    </CardHeader>
                    <div class="flex-1"></div>
                    <CardContent class="flex flex-col align-center">
                        <p class="text-dark text-sm dark:text-white mb-2">Publié le {{ new Date(post.created_at).toLocaleDateString("fr-FR") }}</p>
                        <Button variant="outline" class="font-bold">Lire l'article</Button>
                    </CardContent>
                </NuxtLink>
            </Card>
        </div>
    </div>
</template>

<script setup lang="ts">
import type { Tables } from "~/types/database.types";

const { data: posts } = useFetch<Tables<'blog'>[]>(`http://localhost:3000/api/blog`)
</script>

// src/app/blog/page.tsx
import { getPosts } from "@/actions/blog";
import { Button } from "@/components/ui/button";
import { Card, CardHeader, CardTitle } from "@/components/ui/card";

export default async function Blog({ searchParams }: { searchParams?: { [key: string]: string | string[] | undefined } }) {
    const slug = searchParams?.slug as string | undefined
    const { posts } = await getPosts(slug ? parseInt(slug) : 0)

    return (
        <div className="container mx-auto p-4">
            <h1 className="text-4xl font-bold mb-4">Blog</h1>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {posts.map((post) => (
                <Card key={post.id} className="p-4 rounded-lg shadow border-2 border-dark dark:border-white bg-transparent hover:scale-[1.05] cursor-pointer duration-500">
                    <a href={`/blog/${post.slug}`}>
                        <CardHeader>
                            <CardTitle className="text-4xl font-bold mb-4 text-dark dark:text-white">{post.title}</CardTitle>
                            <p className="text-dark dark:text-white mb-4">Publié le {post.created_at ? new Date(post.created_at).toLocaleDateString("fr-FR") : ""}</p>
                            <Button variant="outline">Lire la suite...</Button>
                        </CardHeader>
                    </a>
                </Card>
            ))}
            </div>
        </div>
    );
}
